config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :posts do
    get :my_posts, on: :collection
    resources :comments
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post

  def new
    @comment = @post.comments.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @comment  = @post.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to posts_path }
        format.js { render :create }
      else
        format.html { render :new }
        format.js { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
  
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.js { render :destroy }
    end
  end  

  private
  def get_post
    @post = Post.find_by(id: params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>content:</strong>
  <%= comment.content %>
</p>
 
<p>
  <strong>User:</strong>
  <%= comment.user.username %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, url: post_comments_path(@post),  method: :post) do |form| %>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="form-group">

    <% @post.comments.each do|comment| %>
      <% if comment.id.present?%>
        <div class="d-flex p-2 comment-box mb-2">
            <i class="fa fa-user user-icon d-flex justify-content-center align-items-center me-3 bg-dark text-white"></i>
            <strong class="card-text text-dark"> <%= comment.user&.username%> : </strong>
            <p class="m-0 px-2 comment-text"><%= comment&.content %> </p>
            <%=comment.created_at&.strftime("%d %b %Y %H:%M:%S") %>
        </div>
      <%end%>
    <%end%>
  </div>

  <div class="modal-footer">
    <%= form.label :content, class: "text-info" do %>
       Add Comment 
    <% end %><br>
    <%= form.text_area :content, class: "form-control" %>
    <%= form.button "Close", type: "reset", class: "btn btn-secondary", data: { dismiss: "modal" } %>
    <%= form.submit "Submit", class: "btn btn-primary", id: "submit" %>
  </div>
<% end %>

app/views/comments/new.html.erb
<div class="modal fade" id="addBookDialog" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="text-center text-info">Add Comment</h4>
      </div>
      <div class="modal-body">
          <%= form_with(model: [ @post, Comment.new ], local: true) do |form| %>

          <%= form.hidden_field :post_id, value: @post.id %>
          <%= form.hidden_field :user_id, value: @post.user.id %>

          <div class="form-group">
            <%= form.label :content, "Content:" %>
            <%= form.text_area :content, class: "form-control" %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= form.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/new.js.erb
$('#exampleModal-body').html("<%= escape_javascript(render partial: 'form', local: { post: @post, comment: @comment }) %>")
$('#modal_header').text('All Comments')
$('#exampleModal').modal('show');