config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :posts do
    get :my_posts, on: :collection
    resources :comments
  end
end

app/models/post.rb
require "image_processing/vips"

class Post < ApplicationRecord
  include Navigable

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :image, presence: true
  validate :image_format
  before_save :convert_to_jpg
  

  ACCEPTABLE_FORMATS = %w[image/png image/jpeg image/bmp].freeze

  scope :by_user, -> (user_id) {
    where(user_id: user_id)
  }

  scope :except_current_user, -> (user_id) {
    where.not(user_id: user_id)
  }

  private

  def image_format
    if image.attached? && !ACCEPTABLE_FORMATS.include?(image.blob.content_type)
      errors.add(:image, 'must be a PNG, JPG, or BMP')
    end
  end

  def convert_to_jpg
    return unless image.attached?

    processed = ImageProcessing::Vips.source(image).convert('jpg')

    image.blob.update(filename: "#{image.blob.filename.base}.jpg", 
                      content_type: 'image/jpg')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_posts, only: %w[index my_posts]

  def index
    @pagy, @posts = pagy @posts.except_current_user(current_user.id)

    respond_to do |format|
      format.html
      format.json {
        render json: { entries: render_to_string(partial: "posts", formats: [:html]), pagination: view_context.pagy_nav(@pagy) }
      }
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
 
  def create
    @post = Post.new(post_params)
    @post.save
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def my_posts
    @pagy, @posts = pagy_countless(@posts.by_user(current_user.id), items: 5)

    respond_to do |format|
      format.html
      format.json {
        render json: { entries: render_to_string(partial: "posts", formats: [:html]), pagination: view_context.pagy_nav(@pagy) }
      }
    end
  end

  private

  def get_posts
    @posts = Post.left_joins(:comments).group('posts.id').order('COUNT(comments.id) DESC')
  end

  def post_params
    params.require(:post).permit(:caption, :image, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_modal.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="text-center text-info" id="modal_header"></h4>
      </div>
      <div class="modal-body" id="exampleModal-body">
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, format: :js, local: false  do |form| %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <% if @post.errors.any? %>
          <div class="alert alert-danger" id="error_explanation">
            <ul>
              <%= @post.errors.full_messages.join(',')%>
            </ul>
          </div>
        <% end %>

        <div class="form-group mb-3">
          <%= form.label :caption %>
          <%= form.text_field :caption, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :image %>
          <%= form.file_field :image, class: 'form-control-file' %>
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>

        <div class="d-flex justify-content-center">
          <%= form.submit 'Save', class: 'btn btn-primary mb-3', style: 'width: 100px;' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 col-sm-8 col-md-8 col-lg-8 mx-auto">
    <% @posts.each do |post| %>
      <%= content_tag :div, id: dom_id(post), class: ["card", "card-body", "mb-2", dom_class(post)] do %>
        <div>
          <div class="card post-card mt-4">
              <div class="d-flex align-items-center justify-content-between user-info-wrap py-2 px-4 bg-dark">
                <div class="d-flex align-items-center">
                  <i class="fa fa-user user-icon d-flex justify-content-center align-items-center me-3"></i>
                <strong class="card-text text-white"> <%= post.user.username %></strong>
                </div>
                <% if current_user.id == post.user.id%>
                  <%= button_to post_path(post), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: 'text-decoration-none' do %>
                      <i class="fa fa-trash text-danger delete-icon"></i>
                  <% end %>
                <%end%>
              </div>

              <p class="card-text px-4 pt-3"><%= post.caption %></p>
              <div class="mb-3">
                <div class="image-box text-center py-4"><%= image_tag post.image, class: "image-wrap" if post.image.attached? %></div>
                <div class="card-body px-4">

                  <div class="d-flex align-items-center">
                    <h6 class="card-subtitle text-muted mb-2">Comments:</h6>
                  </div>
                <% post.comments.order(created_at: :desc).limit(2).each do |comment| %>
                  <div class="d-flex p-2 comment-box">
                    <i class="fa fa-user user-icon d-flex justify-content-center align-items-center me-3 bg-dark text-white"></i>
                    <strong class="card-text text-dark"> <%= comment.user.username %> : </strong>
                    <p class="m-0 px-2 comment-text"><%= comment.content %> </p>
                    <%=comment.created_at.strftime("%d %b %Y %H:%M:%S") %>
                  </div>
                  <br>
                <% end %>

                </div>
                <%= link_to new_post_comment_path(post_id: post.id), remote: 'true', class: 'comment-link d-flex justify-content-center align-items-center me-3 text-primary' do %>
                  <span class= "me-2">Add Comment</span> 
                  <i class="fa fa-comment"></i>
                <%end%>
              </div>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

<%= render partial: "comment_modal"%>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
  $('#exampleModal-body').html("<%= escape_javascript(render partial: 'form', local: { post: @post }) %>")
  $('#modal_header').text('New Post')
  $('#exampleModal').modal('show');
<% else %>
  window.location.href = "<%= my_posts_posts_url %>";
<% end %>

app/views/posts/index.html.erb
<div data-controller="scroll">
  <div data-scroll-target="entries">
    <%= render 'posts' %>
  </div>

  <div data-scroll-target="pagination">
    <% pagy_nav @pagy %>
  </div>
</div>

app/views/posts/my_posts.html.erb
<div data-controller="scroll">
  <div data-scroll-target="entries">
    <%= render 'posts' %>
  </div>

  <div data-scroll-target="pagination">
    <%== pagy_nav @pagy %>
  </div>
</div>

app/views/posts/new.js.erb
$('#exampleModal-body').html("<%= escape_javascript(render partial: 'form', local: { post: @post }) %>")
$('#modal_header').text('New Post')
$('#exampleModal').modal('show');

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><strong>Caption:</strong> <%= @post.caption %></h5>
          <div class="mb-3">
            <%= image_tag @post.image if @post.image.attached?%>
          </div>
          <p class="card-text">
            <strong>User:</strong> <%= @post.user.username %>
          </p>
          <%= render @post.comments %>
        </div>
        <div class="card-footer">
          <div class="btn-group" role="group">
            <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' %>
            <%= link_to 'Back', posts_path, class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>