config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  # get "up" => "rails/health#show", as: :rails_health_check
  resources :posts do
    get :my_posts, on: :collection
    resources :comments
  end
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark py-2 px-4 custom-footer mt-5">
  <p class="text-white mb-0 text-center">copyright @pic_post</p>
</footer>

app/views/layouts/_header.html.erb
<header class="d-flex justify-content-between align-items-center bg-dark py-2 px-4 custom-header">
  <%= link_to posts_path, class: "text-decoration-none" do %>
    <h2 class="text-white">Dashboard</h2>
  <% end %>
  <% if user_signed_in? %>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to 'New post', new_post_path, remote: true, class: 'btn btn-primary me-3 rounded-pill px-4' %>
      <%= link_to 'My post', my_posts_posts_path, class: 'btn btn-primary me-3 rounded-pill px-4' %>
      <div class="text-decoration-none btn btn-light rounded-pill px-4">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PicPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%#= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'rails-ujs' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>